<a href="https://colab.research.google.com/github/padelacruz85/DAF2026/blob/main/%5BDATA_PREPROCESSING%5D_MotorPH_Products_List_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Connecting to google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
#Import libraries
import numpy as np #arithmetic and statistical computations
import pandas as pd #data wrangling and manipulation
import matplotlib.pyplot as plt #Basic Data Viz
import seaborn as sns #Intermediate Statistical Data Viz

from scipy import stats #intermediate statistical computation

In [8]:
#Load Data Sets
df_prodList = pd.read_csv('/content/drive/MyDrive/4thYR_Term1/MO-IT106 - Data Analytics Fundamentals/Week 05/Dataset Preprocessing/[RAW_DATA]_MotorPH_Products_List_2025.csv')
df_salesData = pd.read_csv('/content/drive/MyDrive/4thYR_Term1/MO-IT106 - Data Analytics Fundamentals/Week 05/Dataset Preprocessing/[RAW_DATA]_MotorPH_Sales Data-3rd Quarter-Year 2025.csv')

# **INSPECTING DATA SETS**

In [ ]:
#View the first 10 observations
df_prodList.head(10)

,EntrNo,EntrName,EntrDetails,Manufacturing Date,Acquisiton,UnitPrice
0,1,Honda CBR500R,"Sport / Parallel-twin, liquid-cooled, 471cc, 6...",2021,2023,389000
1,2,Yamaha MT-15,"Naked bike / Single cylinder, liquid-cooled, 1...",2022,2023,178000
2,3,Kawasaki Ninja 400,"Sport / Parallel-twin, liquid-cooled, 399cc, 6...",2023,2024,340000
3,4,Suzuki Raider R150 Fi,"Underbone / Single cylinder, liquid-cooled, 15...",2020,2021,119900
4,5,Royal Enfield Classic 350,"Classic / Single cylinder, air-cooled, 349cc, ...",2022,2023,250000
5,6,CFMoto 300NK,"Naked bike / Single cylinder, liquid-cooled, 2...",2021,2022,165000
6,7,Bristol Veloce 500,"Cafe racer / Twin cylinder, air-cooled, 471cc,...",2022,2023,328000
7,8,KTM Duke 200,"Naked bike / Single cylinder, liquid-cooled, 1...",2023,2024,178000
8,9,Yamaha XSR155,"Retro / Single cylinder, liquid-cooled, 155cc,...",2022,2023,182000
9,10,Bajaj Dominar 400,"Sport touring / Single cylinder, liquid-cooled...",2021,2022,199900

In [ ]:
#View the last 15 observations
df_prodList.tail(15)

,EntrNo,EntrName,EntrDetails,Manufacturing Date,Acquisiton,UnitPrice
35,36,Benelli 502C,"Cruiser / Parallel-twin, liquid-cooled, 500cc,...",2022,2023,349000
36,37,Moto Morini X-Cape 650,"Adventure / Parallel-twin, liquid-cooled, 649c...",2023,2024,369000
37,38,Yamaha FZi 150,"Street / Single cylinder, air-cooled, 149cc, 5...",2021,2022,99900
38,39,Vespa GTS Super 300,"Scooter / Single cylinder, liquid-cooled, 278c...",2023,2024,398000
39,40,Kawasaki KLX 230,"Dual-sport / Single cylinder, air-cooled, 233c...",2022,2023,199000
40,41,BMW R nineT,"Heritage / Flat twin, air/oil-cooled, 1170cc, ...",2023,2024,995000
41,42,Honda Rebel 1100,"Cruiser / Parallel-twin, liquid-cooled, 1084cc...",2023,2024,650000
42,43,KTM 790 Duke,"Naked bike / Parallel-twin, liquid-cooled, 799...",2023,2024,599000
43,44,CFMoto 300SR,"Sport / Single cylinder, liquid-cooled, 292cc,...",2023,2024,165000
44,45,Italjet Dragster 200,"Scooter / Single cylinder, liquid-cooled, 181c...",2023,2024,289000
45,46,Yamaha Serow 250,"Dual-sport / Single cylinder, air-cooled, 249c...",2020,2021,299000
46,47,Suzuki Burgman Street 125,"Scooter / Single cylinder, air-cooled, 124cc, CVT",2023,2024,80900
47,48,Zontes GK350,"Cafe racer / Single cylinder, liquid-cooled, 3...",2023,2024,269000
48,49,Moto Guzzi V7 Stone,"Heritage / V-twin, air-cooled, 853cc, 6-speed",2022,2023,689000
49,50,SYM Husky 150,"Underbone / Single cylinder, air-cooled, 150cc...",2022,2023,72900

In [ ]:
#Check the number of rows & columns (dimensions)
df_prodList.shape

(50, 6)

In [ ]:
df_prodList.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EntrNo              50 non-null     int64
 1   EntrName            50 non-null     object
 2   EntrDetails         50 non-null     object
 3   Manufacturing Date  50 non-null     int64
 4   Acquisiton          50 non-null     int64
 5   UnitPrice           50 non-null     int64
dtypes: int64(4), object(2)
memory usage: 2.5+ KB

In [ ]:
df_prodList = df_prodList.astype({
    "EntrName": 'string',
    "EntrDetails": 'string',
    "UnitPrice": 'float'
})

In [ ]:
df_prodList.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EntrNo              50 non-null     int64
 1   EntrName            50 non-null     string
 2   EntrDetails         50 non-null     string
 3   Manufacturing Date  50 non-null     int64
 4   Acquisiton          50 non-null     int64
 5   UnitPrice           50 non-null     float64
dtypes: float64(1), int64(3), string(2)
memory usage: 2.5 KB